accounts/urls.py
from django.conf.urls import url

# from accounts.views import LoginView
from .import views



app_name = 'accounts'


urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    # url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

porownywarka/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from porownanie_cen.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^porownanie_cen/', include('porownanie_cen.urls')),
    url(r'^wszystkie_ceny/', include('wszystkie_ceny.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', login_required(IndexView.as_view()), name="home"),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Nazwa użytkownika'},
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'placeholder': 'Hasło'},
    ))
    class Meta:
        fields = ['Username', 'Password']

accounts/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.views import View

from accounts.forms import LoginForm

@staff_member_required
def signup_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log in
            return redirect('porownanie_cen:index')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html',{'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # log in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('porownanie_cen:index')


    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('porownanie_cen:index')

accounts/templates/accounts/login.html
{% extends 'porownanie_cen/base.html' %}

{% block body %}
{% load static %}

  <div class="container">

    <form class="form-signin d-block mx-auto mt-3 bg-light p-3 border border-dark rounded " action="{% url 'accounts:login' %}" method="post" style="max-width:400px;">
      <img class="d-block mx-auto mb-2" src="{% static 'accounts/' %}img/user-ninja-solid-rece.png" alt="int-ninja" width="150">

      {% csrf_token %}

      {{form.username}}
      {{form.password}}
      {% if form.errors %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger m-1">
              <strong>Niewłaściwy login lub hasło, spróbuj ponownie...</strong>
          </div>
        {% endfor %}
      {% endif %}

      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
      {% endif %}
      <button type="submit" class="btn btn-lg btn-primary btn-block mt-1">Zaloguj</button>
    </form>

  </div> <!-- /container -->
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'porownanie_cen/base.html' %}

{% block body %}


<div class="container">
  <h1>DODAJ </h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Sign in</button>
      </div>
    </div>
  </form>
</div>

{% endblock %}