accounts/urls.py
from django.conf.urls import url

# from accounts.views import LoginView
from .import views



app_name = 'accounts'


urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    # url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

porownanie_cen/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
app_name = 'porownanie_cen'

urlpatterns = [
    #/porownanie_cen
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),



    #porownanie_cen/1/
    url(r'^(?P<pk>[0-9]+)/$', views.brand_details, name='detail'),

    # powownanie_cen/brand/add/
    url(r'brand/add/$', views.brand_create, name='brand-add'),

    # powownanie_cen/brand/23/
    url(r'brand/(?P<pk>[0-9]+)/$', login_required(views.BrandUpdate.as_view()),name='brand-update'),

    # powownanie_cen/brand/23/delete/
    url(r'brand/(?P<pk>[0-9]+)/delete/$', login_required(views.BrandDelete.as_view()), name='brand-delete'),


]


porownywarka/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from porownanie_cen.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^porownanie_cen/', include('porownanie_cen.urls')),
    url(r'^wszystkie_ceny/', include('wszystkie_ceny.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', login_required(IndexView.as_view()), name="home"),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wszystkie_ceny/urls.py
from django.conf.urls import url
from . import views

app_name = 'wszystkie_ceny'

urlpatterns = [
    url(r'^produkty/$', views.wszystkie_ceny_view, name='produkty'),
]

porownanie_cen/models.py
import os


from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse

def get_unique_slug(model,field_name,value):
    max_length = model._meta.get_field(field_name).max_length
    slug = slugify(value)
    num = 1
    unique_slug = '{}-{}'.format(slug[:max_length - len(str(num)) - 1], num)
    while model.objects.filter(** {field_name: unique_slug}).exists():
        unique_slug = '{}-{}'.format(slug[:max_length - len(str(num)) - 1], num)
        num += 1
    return unique_slug


class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(db_column='nazwa', max_length=200)
    logo = models.FileField(blank=True, null=True)
    icon = models.CharField(db_column='icon', max_length=200,default='fas fa-rocket fa-5x')

    def __str__(self):
        return self.nazwa

    def get_absolute_url(self):
        return reverse('porownanie_cen:detail', kwargs={'pk': self.pk})

    class Meta:
        managed = True
        db_table = 'brandy'

@receiver(models.signals.post_delete, sender=Brand)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.logo:
        if os.path.isfile(instance.logo.path):
            os.remove(instance.logo.path)

@receiver(models.signals.pre_save, sender=Brand)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).logo
    except sender.DoesNotExist:
        old_file = None

    new_file = instance.logo

    if not old_file == new_file:
        if old_file:
            os.remove(old_file.path)


class Produkt(models.Model):
    klucz = models.CharField(db_column='klucz', max_length=128)
    kodtowaru = models.CharField(db_column='kodTowaru', primary_key=True, max_length=128)
    kontrahentkod = models.CharField(db_column='kontrahentKod', max_length=64)
    kontrahentcennik = models.CharField(db_column='kontrahentCennik', max_length=16)
    opis = models.CharField(max_length=255, blank=True, null=True)
    gruparabatowa_1 = models.CharField(db_column='grupaRabatowa_1', max_length=64, blank=True, null=True)
    gruparabatowa_2 = models.CharField(db_column='grupaRabatowa_2', max_length=64, blank=True, null=True)
    gruparabatowa_3 = models.CharField(db_column='grupaRabatowa_3', max_length=64, blank=True, null=True)
    cenakatalogowa = models.DecimalField(db_column='cenaKatalogowa', max_digits=12, decimal_places=4, blank=True,
                                         null=True)
    walutakatalogowa = models.CharField(db_column='walutaKatalogowa', max_length=3, blank=True, null=True)
    cenakoncowa = models.DecimalField(db_column='cenaKoncowa', max_digits=12, decimal_places=4, blank=True, null=True)
    walutakoncowa = models.CharField(db_column='walutaKoncowa', max_length=3, blank=True, null=True)
    cenakatalogowa_eur = models.DecimalField(db_column='cenaKatalogowa_EUR', max_digits=12, decimal_places=4,
                                             blank=True, null=True)
    cenakoncowa_eur = models.DecimalField(db_column='cenaKoncowa_EUR', max_digits=12, decimal_places=4, blank=True,
                                          null=True)
    moq = models.DecimalField(max_digits=12, decimal_places=0, blank=True, null=True)
    dataimportu = models.DateField(db_column='dataImportu', null=True, blank=True, auto_now_add=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def __str__(self):
        return self.kodtowaru

    class Meta:
        managed = True
        db_table = 'produkty'
        unique_together = (('kodtowaru', 'kontrahentkod', 'kontrahentcennik'),)


porownanie_cen/forms.py


from django import forms
from . import models



class CreateBrand(forms.ModelForm):
    nazwa = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Nazwa Brandu',
               }
    ))

    class Meta:
        model = models.Brand
        fields = ['nazwa', 'logo']


class UpdateBrand(CreateBrand):
    class Meta:
        model = models.Brand
        fields = ['nazwa', 'logo']

porownanie_cen/views.py
import re

from django.db.models import Min
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from porownanie_cen import forms
from porownanie_cen.forms import UpdateBrand
from .models import Brand, Produkt
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'porownanie_cen/index.html'
    context_object_name = 'all_brands'

    def get_queryset(self):
        return Brand.objects.all()


class BrandUpdate(UpdateView):
    model = Brand
    form_class = UpdateBrand
    # fields = ['nazwa', 'logo']
    success_url = reverse_lazy('porownanie_cen:index')


class BrandDelete(DeleteView):
    model = Brand
    success_url = reverse_lazy('porownanie_cen:index')

    # usuwanie bez potwierdzającego template
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


@login_required()
def brand_create(request):
    if request.method == 'POST':
        form = forms.CreateBrand(request.POST, request.FILES)
        if form.is_valid():
            brand = form.save(commit=False)
            brand.save()

            return redirect('porownanie_cen:index')
    else:

        form = forms.CreateBrand()
    return render(request, 'porownanie_cen/brand_add.html', {'form': form})


def brand_details(request, pk):
    query = request.GET.get('q')
    codes_to_query = None
    by_price = []
    all_products = Produkt.objects.raw(
        "select * from produkty where brand_id ={} and kodtowaru ='{}' ".format(pk, query))
    base_view = Produkt.objects.raw("select * from produkty where brand_id ={} limit 10".format(pk))
    brand = Brand.objects.raw("select id,nazwa from brandy where id={}".format(pk))
    final_result = []
    code_price = []
    brand_id = pk
    kontrahenci = Produkt.objects.values('kontrahentkod').distinct().filter(brand_id=pk)
    kontrahenci_length = len(kontrahenci)
    result = []
    in_porownanie_cen = True

    if query:
        codes_to_query = query.splitlines()
        for code in codes_to_query:
            kod_query = code.replace("'", '')
            for char in code:
                    if char in re.sub(r'[a-zA-Z0-9]', '', char):
                        code = code.replace(char, "")

            if code != '':
                result = Produkt.objects.values('klucz', 'kodtowaru').filter(kodtowaru=kod_query, brand_id=pk).annotate(
                    Min('cenakoncowa_eur'))
                if result:
                    result = list(result)
                    result.append("BY_KOD_TOWARU")
                    code_price.append(result)

                    for kontrahent in kontrahenci:
                        price = Produkt.objects.values('kodtowaru', 'cenakoncowa_eur', 'kontrahentkod').filter(
                            kontrahentkod=kontrahent['kontrahentkod'], kodtowaru=kod_query, brand_id=pk)
                        by_price.append(price)
                else:
                    result = Produkt.objects.values('klucz', 'kodtowaru').filter(klucz=code, brand_id=pk).annotate(
                        Min('cenakoncowa_eur'))
                    if result:
                        result = list(result)
                        result.append("BY_KLUCZ")
                        result.append(kod_query)
                        code_price.append(result)
                    else:
                        code_price.append(code)
                    # if result:
                        # code_price.append(result)

                    for kontrahent in kontrahenci:
                        price = Produkt.objects.values('klucz', 'cenakoncowa_eur', 'kontrahentkod').filter(
                            kontrahentkod=kontrahent['kontrahentkod'], klucz=code, brand_id=pk)
                        by_price.append(price)

    for result in by_price:
        final_result.append(result.values('kontrahentkod', 'cenakoncowa_eur', 'klucz').order_by('cenakoncowa_eur'))

    context = {
        'products': all_products,
        'base_view': base_view,
        'brand': brand,
        'kontrahenci': kontrahenci,
        'query': query,
        'codes_to_query': codes_to_query,
        'by_price': by_price,
        'final_result': final_result,
        'kontrahenci_length': kontrahenci_length,
        'code_price': code_price,
        'brand_id': brand_id,
        'result': result,
        'in_porownanie_cen':in_porownanie_cen,

    }
    return render(request, 'porownanie_cen/produkty.html', context)

porownanie_cen/templates/porownanie_cen/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>
    INT
    {% if in_porownanie_cen %}-
    {% for item in brand %}
      {{item.nazwa}}
    {% endfor %}
    {% endif %}
    {% if in_wszystkie_produkty %}-
    WSZYSTKIE PRODUKTY
    {% endif%}

  </title>

  <!--static-->
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css"  href="{% static 'porownanie_cen/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script src="{% static 'porownanie_cen/myJS.js' %}"></script>




  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
</head>
<body class="bg-secondary" onload="myFunction()">
<nav class="navbar navbar-dark bg-black navbar-expand-sm p-0"  style="background-color:black;">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img class="rounded" src="{% static 'porownanie_cen/' %}img/3000px.png" alt="" height="30">
      </a>
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#topNavBar">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse expand-lg "id="topNavBar">
        <ul class="nav navbar-nav mr-auto text-center">
          <li class="nav-item ">
            <a class="btn text-light" href="{% url 'porownanie_cen:index' %}"> PORÓWNYWARKA</a>
          </li>
          <li class="nav-item">
            <a class="btn text-light" href="{% url 'wszystkie_ceny:produkty' %} ">CENNIKI</a>
          </li>

          <li class="m-0 ml-lg-5">
              {% if in_wszystkie_produkty %}
              <p class="btn text-light m-0 font-weight-bold cursor-default" style="cursor:default;">
                WSZYSTKIE PRODUKTY
              </p>
              {% endif%}
              {% if in_porownanie_cen %}

                <a class=" btn text-light m-0 font-weight-bold" href="{% url 'porownanie_cen:index' %}">
                  {% for item in brand %}
                    {{ item.nazwa}}
                  {% endfor %}
                </a>
              
            <div class="dropdown float-md-right ">
              <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Wprowadź kody
              </button>
              <div class="dropdown-menu dropdown-menu-center  p-0" aria-labelledby="dropdownMenuButton">
                <form class="form" method="get" action="" >
                  <textarea id="txt1" class="form-control p-0" rows="15"   type="text" name="q"  placeholder="Wyszukaj wiele" style="z-index:99">{{ request.GET.q}}</textarea>
                  <button class="btn btn-info btn-block" type="submit" value="szukaj">Szukaj</button>
                </form>
              </div>
            </div>
          </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav nabar-right text-center">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <div class="btn-group dropleft">
               <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Użytkownik
               </button>
               <div class="dropdown-menu  text-center">
                 <span>{{user}}</span>

                 {% if request.user.is_superuser %}
                 <div>
                   <ul class="nav navbar-nav">
                     <li class="navbar-item">
                       <a class="btn btn-info btn-sm text-light" href="{% url 'porownanie_cen:brand-add' %}"> DODAJ BRAND</a>
                     </li>
                     <li class="navbar-item">
                       <a class="btn btn-secondary text-light btn-sm" href="{% url 'accounts:signup' %}">+</a>
                     </li>
                   </ul>
                 </div>
                 {% endif %}
                 <form class="form" action="{% url 'accounts:logout' %}" method="post">
                   {% csrf_token %}
                   <button class="btn btn-warning btn-sm text-light mr-1" type="submit">Wyloguj</button>
                 </form>
               </div>
             </div>
             {% endif %}
          </li>
        </ul>
      </div>
  </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

porownanie_cen/templates/porownanie_cen/brand_add.html
{% extends 'porownanie_cen/base.html' %}



{% block body %}
<div class="container bg-light w-50">
  <h2 class="text-center">DODAJ BRAND</h2>
  <form class="form p-3" action="{% url 'porownanie_cen:brand-add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form">
      <div class="row d-flex">
        <div class="col-5 my-auto">{{ form.nazwa}}</div>
        <div class="col-5 ">Logo: {{ form.logo}}</div>
        <div class="col-2 my-auto">
          <button type="submit" class="btn btn-info" value="Create">ZAPISZ</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

porownanie_cen/templates/porownanie_cen/brand_form.html
{% extends 'porownanie_cen/base.html' %}



{% block body %}

<div class="container bg-light w-50">
  <h2 class="text-center">EDYTUJ BRAND</h2>
  <form class="form p-3" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form">
      <div class="row ">
        <div class="col-12 ">{{ form.nazwa}}</div>
        <div class="col-12 ">{{ form.logo}}</div>
        <div class="col-12 mt-2">
          <button type="submit" class="btn btn-info" value="Create">ZAPISZ</button>
        </div>
      </div>
    </div>
  </form>
</div>


{% endblock %}

porownanie_cen/templates/porownanie_cen/index.html
{% extends 'porownanie_cen/base.html' %}

{% block body %}
{% load static %}

{% if user.is_authenticated %}
<div class="container-fluid p-3 mb-0 shadow shadow-lg" style="background:url({% static 'porownanie_cen/' %}img/light_blue.png); background-repeat:no-repeat; background-position: center center">
  <h1 class="font-weight-light text-center text-muted">Porównywarka Cen by INT-TECHNICS</h1>
  <p class="lead text-center text-muted">Witaj {{user}}!</p>
</div>
{% endif %}
<div class="container-fluid" style="height:100%;">
  <div class="container pt-5 w-50">
    <div class="row ">
    {% for brand in object_list %}

      <div class="col-12 col-md-6 col-lg-4 text-center">
        <a class=" text-light mx-auto btn" href="{% url 'porownanie_cen:detail' brand.id %}">
          <div class="">
            <!--<i class="{{brand.icon}} text-light"></i>-->
            {% if brand.logo %}
            <img class="rounded border border-dark" src="{{ brand.logo.url}}" width="120">
            {% endif %}
          </div>
        </a>
        {% if request.user.is_superuser %}
        <div class="mt-1">

          <form  action="{% url 'porownanie_cen:brand-delete' brand.id %}" method="post">
          <div class="btn-group mb-2" role="group">
            <a  class="btn btn-secondary {% if not request.user.is_superuser %} disabled {% endif %}" href="{% url 'porownanie_cen:brand-update' brand.id%}">
              <i class="fas fa-edit text-light"></i>
            </a>
            <a  href="{% url 'porownanie_cen:detail' brand.id %}" class="btn btn-secondary text-light">+</a>
              {% csrf_token %}
              <input type="hidden" name="brand_id" value="{{brand.id}}"/>
              <button type="submit" class="btn btn-secondary" {% if not request.user.is_superuser %} disabled {% endif %} onclick="return confirm('Usunąć {{brand.nazwa}} i wszystkie pozycje cennika?')" >
                <i class="fas fa-trash-alt text-dark"></i>
              </button>
            </form>
          </div>
        </div>
      {% endif %}
      </div>
    {% endfor %} <!--# all_brands-->
    </div>
  </div>
</div>


<!--<div class="container-fluid p-0 ">-->

  <!--<div class="col-6 mx-auto" style="">-->

    <!--<ul class="list-group ml-0  pt-5">-->
    <!--{% for brand in object_list %}-->

      <!--<li class="list-group-item d-flex  align-items-center py-1 bg-secondary ">-->

        <!--<a class="text-light text-left mx-auto btn" href="{% url 'porownanie_cen:detail' brand.id %}">-->
           <!--<span class="">{{brand.nazwa}}</span>-->
        <!--</a>-->
        <!--{% if brand.logo %}-->
        <!--<img class="img-thumbnail ml-1" src="{{ brand.logo.url }}" width="50" height="50">-->
        <!--{% else %}-->
        <!--<img class="img-thumbnail ml-1" src="{% static 'porownanie_cen/' %}img/RECE.png" width="50" height="50">-->
        <!--{% endif %}-->
        <!--<a class="btn btn-light mx-2 px-3" href="{% url 'porownanie_cen:brand-update' brand.id%}">-->
          <!--<i class="fas fa-edit text-primary"></i>-->
        <!--</a>-->
        <!--<form action="{% url 'porownanie_cen:brand-delete' brand.id %}" method="post" >-->
          <!--{% csrf_token %}-->
          <!--<input type="hidden" name="brand_id" value="{{brand.id}}"/>-->
          <!--<button type="submit" class="btn btn-light px-3" onclick="return confirm('Usunąć {{brand.nazwa}} i wszystkie pozycje cennika?')" >-->
            <!--<i class="fas fa-trash-alt text-dark"></i>-->
          <!--</button>-->
        <!--</form>-->
      <!--</li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
  <!--</div>-->



  </div>







{% endblock %}

porownanie_cen/templates/porownanie_cen/produkty.html
{% extends 'porownanie_cen/base.html' %}

{% block body %}
{% load static %}
  {% if brand %}
  {% for item in brand %}
    <h3 class="text-center d-block d-md-none"> {{ item.nazwa}}</h3>
  {% endfor %}
  {% endif %}
  <div class="row mx-2">
    <div class="col-12 col-lg-4 p-0">
      <table class="w-100" id="prices" >
        <thead>
          <tr class="bg-secondary text-center text-warning">
            <th colspan="2" class="border border-right-0 text-right">Razem:</th>
            <th class="border border-left-0" id="lowest_sum">0.00</th>
          </tr>
          <tr class="bg-primary text-light text-center" >
            <th class="border p-1" scope="col">
              <button class="btn py-0 px-1 btn-tarnsparent text-white far fa-copy" onclick="copy()"  data-toggle="tooltip" data-placement="top" title="Kopiuj do Schowka" id="copyButton"></button>
              <small>KOD</small>
            </th>
            <th class="border  p-1" scope="col"><small>Ilość</small></th>
            <th class="border p-1" scope="col"><small>CENA</small></th>
          </tr>
        </thead>
        {% if code_price %}
        <tbody>

          {% for code in code_price %}
            <tr class="text-center">
              {% if code.0.kodtowaru %}
                {% if code.1 == "BY_KLUCZ" %}

                <td  class="codes-background border border-dark border-left-0  text-dark">{{code.0.kodtowaru}}<i class="fas fa-exclamation-circle ml-2" data-toggle="tooltip" data-placement="right" title="Nie znaleziono kodu: {{code.2}}. Wyszukano po kluczu: {{code.0.klucz}}"</i></td>
                {% else %}
                <td nowrap class="codes-background border border-dark border-left-0   text-dark " >{{code.0.kodtowaru}}</td>
                {% endif %}

                <td class="table-background  border border-dark text-dark ">1</td>
                <!--suppress XmlDuplicatedId -->
                {% if code.0.cenakoncowa_eur__min %}
                  <td class="lowest-background  border border-dark text-light " id="lowest_{{forloop.counter}}">{{code.0.cenakoncowa_eur__min}}</td>
                  {% else %}
                  <td class="lowest-background  border border-dark text-light " id="lowest_{{forloop.counter}}">0</td>
                {% endif %}
              {% else %}
                <td class="bg-danger  border border-dark text-dark">
                  {{code}}
                </td>
                <td class="bg-danger  border border-dark text-dark " >0</td>
                <!--suppress XmlDuplicatedId -->
                <td class="bg-danger  border border-dark text-light " id="lowest_{{forloop.counter}}">0</td>
              {% endif %}
            </tr>
          {% endfor %}

        </tbody>
        {% else %}
        <tbody>
          <tr class="text-center">
              <td  class="codes-background border border-dark border-left-0  text-dark"><i class="fas fa-exclamation-circle ml-2"</i></td>
              <td class="table-background  border border-dark text-dark ">1</td>
              <td class="table-background   border border-dark text-dark " >0</td>
          </tr>
          <tr class="text-center">
              <td  class="codes-background border border-dark border-left-0  text-dark"><i class="fas fa-exclamation-circle ml-2"</i></td>
              <td class="table-background  border border-dark text-dark ">1</td>
              <td class="table-background   border border-dark text-dark " >0</td>
          </tr>
          <tr class="text-center">
              <td  class="codes-background border border-dark border-left-0  text-dark"><i class="fas fa-exclamation-circle ml-2"</i></td>
              <td class="table-background  border border-dark text-dark ">1</td>
              <td class="table-background   border border-dark text-dark " >0</td>
          </tr>
          <tr class="text-center">
              <td  class="codes-background border border-dark border-left-0  text-dark"><i class="fas fa-exclamation-circle ml-2"</i></td>
              <td class="table-background  border border-dark text-dark ">1</td>
              <td class="table-background   border border-dark text-dark " >0</td>
          </tr>
        </tbody>
        {% endif %}
      </table>
    </div>

    <div class="col-12 col-lg-8 p-0">
      <table class="w-100" id="result">
        <thead>
          <tr class="text-center bg-secondary  text-warning">
            {% for kontrahent in kontrahenci %}
            <th class="border" id="cena_kontrahent_{{forloop.counter}}">
              0.00
            </th>
            {% endfor %}
          </tr>
          <tr  class="bg-primary text-center border border-dark text-light">
            {% for kontrahent in kontrahenci %}
            <th nowrap class="border p-1" >
              <small>{{ kontrahent.kontrahentkod }}</small>
            </th>
          {% endfor %}
          </tr>
        </thead>
        {% if final_result %}
        <tbody>
          {% if final_result %}
            <tr class="row_result" >
          {% endif %}
            {% for item in final_result %}
              {% if  item.0.cenakoncowa_eur %}
                <td class="text-center table-background  border border-dark text-dark" id="{{forloop.counter}}">{{ item.0.cenakoncowa_eur }}</td>
              {% else %}
                <td class="text-center table-background border border-dark text-danger" id="{{forloop.counter}}">N/A</td>
              {% endif %}
              <!-- if last column in row -->
              {% with num=kontrahenci_length %}
                {% if forloop.counter|divisibleby:num and not forloop.last %}
              </tr>
              <tr class="row_result" >
            {% endif %}
          {% endwith %}
        {% endfor %}
      </tr>
        </tbody>
        {% else %}
        <tbody>
          <tr>
            {% for kontrahent in kontrahenci %}
            <td class="text-center table-background border border-dark text-danger" id="{{forloop.counter}}">N/A</td>
            {% endfor %}
          </tr>
          <tr>
            {% for kontrahent in kontrahenci %}
            <td class="text-center table-background border border-dark text-danger" id="{{forloop.counter}}">N/A</td>
            {% endfor %}
          </tr>
          <tr>
            {% for kontrahent in kontrahenci %}
            <td class="text-center table-background border border-dark text-danger" id="{{forloop.counter}}">N/A</td>
            {% endfor %}
          </tr>
          <tr>
            {% for kontrahent in kontrahenci %}
            <td class="text-center table-background border border-dark text-danger" id="{{forloop.counter}}">N/A</td>
            {% endfor %}
          </tr>
        </tbody>
        {% endif %}
      </table>
    </div>
  </div>
</div>
</div>
<textarea name="name" rows="1" cols="20" id="copy" style="opacity:0;"></textarea>

{% endblock %}